/*
 * Customer Support data layer.
 * API documentation for Abstraction data layer for Customer support Front office applications.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Authentication.
 */
public with sharing class ContextAuthentication {
    /**
     * This field represents whether the customer was authenticated or not.
     * @return authenticated
     */
    @AuraEnabled
    public Boolean authenticated { get; set; }

    /**
     * Methods to get authenticated by OMNI channel.
     * @return authMethod
     */
    @AuraEnabled
    public String auth_method { get; set; }

    /**
     * Channel id which is authenticated.
     * @return authChannelId
     */
    @AuraEnabled
    public String auth_channel_id { get; set; }

    /**
     * Customer session ID for any channel.
     * @return globalSessionId
     */
    @AuraEnabled
    public String global_session_id { get; set; }

    /**
     * Channel session ID for the given channel.
     * @return channelSessionId
     */
    @AuraEnabled
    public String channel_session_id { get; set; }

    /**
     * Step up details.
     * @return stepUp
     */
    @AuraEnabled
    public ContextStepup step_up { get; set; }
    
}