public class FinancialInstrumentDO {
    public String wallet_id;
    public String logo_url;
    public String issuer_name;
    public String name_on_file;
    public String financial_instrument_type;
    public String subtype;
    public String last_digits;
    public Datetime expiry_date;
    public String status;
    public String confirmation_status;
    public MoneyDO paypal_credit_limit;
    public MoneyDO paypal_credit_usage;
}