public class SecondaryUserDO {
    public String login_id;
    public String party_id;
    public String full_name;
    public String first_name;
    public String last_name;
    public String logo_url;
    public Integer age;
    public Boolean has_permission_to_speak;
    public ComplianceDO compliance;
    public List<EmailDO> emails;
    public List<PhoneDO> phone_numbers;
    public List<AddressDO> addresses;
}